name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false || github.event.pull_request.merged == true
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          git clone https://github.com/david050602/jenkins_test.git
          cd jenkins_test
          cat Jenkins_file_test
          echo "Running tests on the pull request"

  merge-actions:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Perform Post-Merge Actions
        run: |
          echo "Executing post-merge"
